stages:
  - step1
  - step2
  - step3

job_1a:
  stage: step1
  script: echo job_1a

job_1b:
  stage: step1
  script: echo job_1b  
  only:
    - /^issue-.*$/
job_1c:
  stage: step1
  script: echo job_1c
  only:
    - /^hotfix-.*$/

job_2a:
  stage: step2
  script: echo job_2a  
  only:
    - basic_pipeline
job_2b:
  stage: step2
  script: ego job_2b
  allow_failure: true  

job_3a:
  stage: step3
  script: echo job_3a  

job_3b:
  stage: step3
  script: ego job_3b
