variables:
  NEXUS_URL: http://192.168.178.48:8083
  NEXUS_USER: admin
  NEXUS_PASSWORD: admin123 
build:
  stage: build
  tags:
    - docker_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - wget -O app.jar "http://192.168.178.48:8081/service/rest/v1/search/assets/download?repository=maven-snapshots&group=org.javacream.training&name=org.javacream.training.store.web&sort=version"
    - echo "{\"auths\":{\"$NEXUS_URL\":{\"username\":\"$NEXUS_USER\",\"password\":\"$NEXUS_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --insecure --destination 192.168.178.48:8083/javacream/test:1.0
  only:
    - spring_boot_application_kaniko

